### ISSUE TITLE
Do we need to create a new shareType::SCIENCEMESH ?

### ISSUE THREAD

**Issue by Triantafullenia-Doumani** [pondersource/nc-sciencemesh#111]
### Why yes:

When we manage a share 'between' Reva and Nextcloud, we are doing this via the Sciencemesh app, so it makes sense that the type of the share is 'Sciencemesh' type

### Why not:

 In the RevaCotroller.php, we implement these methods for sharing:

* Share()
* addShare()
* GetShare()
* Unshare()
* UpdateShare()
* ListShares()
* ListReceivedShares()
* GetReceivedShare()
* UpdateReceivedShare()

All of them handle each share as a ['Share' object](https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Share20/Share.php) -> [Share implements IShare](https://github.com/nextcloud/server/blob/215aef3/lib/public/Share/IShare.php).

So, if we want to generate a new ShareType:`public const TYPE_SCIENCEMESH = 14`, that would be incompatible with the [Share20](https://github.com/nextcloud/server/tree/9068fd4a21f866ab23699f4840aafd5024e76198/lib/private/Share20) library, which handles the shares.

**Comment by Triantafullenia-Doumani** [comment]
### Why yes:

When we manage a share 'between' Reva and Nextcloud, we are doing this via the Sciencemesh app, so it makes sense that the type of the share is 'Sciencemesh' type

### Why not:

1. In the RevaCotroller.php, we implement these methods for sharing:

* Share()
* addShare()
* GetShare()
* Unshare()
* UpdateShare()
* ListShares()
* ListReceivedShares()
* GetReceivedShare()
* UpdateReceivedShare()

All of them handle each share as a ['Share' object](https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Share20/Share.php) -> [Share implements IShare](https://github.com/nextcloud/server/blob/215aef3/lib/public/Share/IShare.php).

So, if we want to generate a new ShareType:`public const TYPE_SCIENCEMESH = 14`, that would be incompatible with the [Share20](https://github.com/nextcloud/server/tree/9068fd4a21f866ab23699f4840aafd5024e76198/lib/private/Share20) library, which handles the shares.

2. The only info that we get from `shareType::SCIENCEMESH` is that the sharing is 'between' Reva and Nextcloud

:point_down: 

So, **What** are we sharing?

**Comment by michielbdejong** [comment]
Done, see https://github.com/pondersource/sciencemesh-nextcloud#standard-setup-recommended-for-triantafullenia-ismoil-yvo-b%C3%A4nz-navid
