### ISSUE TITLE
Get Reva work for ocm-sharing with Nextcloud

### ISSUE THREAD

**Issue by Triantafullenia-Doumani** [pondersource/nc-sciencemesh#113]
### Reva ocm-sharing commands: 

- [x] ocm-share-create 
- [ ] ocm-share-list-received 
- [ ] ocm-share-list 
- [ ]  ocm-share-remove 
- [ ]  ocm-share-update-received 
- [ ]  ocm-share-update 

### Nextcloud methods for sharing 

- [x]  addSentShare()
- [x] addReceivedShare()
- [x] GetSentShare()
- [x] GetReceivedShare()
- [x] Unshare()
- [x] UpdateShare()
- [ ] UpdateReceivedShare()
- [x] ListSentShares()
- [x] ListReceivedShares()

**Comment by michielbdejong** [comment]
This is an overview issue and doesn't represent any task itself.
See also https://github.com/orgs/pondersource/projects/1/views/1 for an overview of the entire sciencemesh-nextcloud project.
