### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#119]
We need to add some UI to our app.

See:

[Deliverable 3a (Sciencemesh-Nextcloud).pdf](https://github.com/pondersource/nc-sciencemesh/files/7510966/Deliverable.3a.Sciencemesh-Nextcloud.pdf)

**Comment by michielbdejong** [comment]
Note the html is already in the app! (see Slack)

**Comment by ishifoev** [comment]
I don't see here, HTML files if you are saying about sciencemesh project.

**Comment by michielbdejong** [comment]
Correct, sorry! The HTML files were missing. They're being added now, see https://github.com/pondersource/nc-sciencemesh/pull/120
