### ISSUE TITLE
"outbound http controller"

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#122]
we should have a bit of code that all outgoing rest calls to reva pass through

draft code I'm using now: https://github.com/pondersource/nc-sciencemesh/commit/79b3ebad#diff-9b4535b670745f8ec247f668fc73f00f351dbf2c9f86332ec5fe042d44f5c5baR41

**Comment by ylebre** [comment]
https://github.com/pondersource/nc-sciencemesh/pull/131
