### ISSUE TITLE
Problem with http://localhost:8080/index.php/apps/sciencemesh/notifications

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#123]
Exception":"Exception","Message":"Call to a member function getUID() on null in file '/Users/michiel/gh/nextcloud/server/apps/sciencemesh/lib/Controller/AppController.php' line 75

**Comment by ishifoev** [comment]
https://github.com/pondersource/nc-sciencemesh/commit/027c7b8e83f706b355e1f29f777ab354bea6994d

**Comment by ishifoev** [comment]
I just fix the problem you can close it. But the firs you need to check the problem.

**Comment by michielbdejong** [comment]
Great work!! \o/
