### ISSUE TITLE
Implement api/user/GetUser

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#148]
Not sure what I'm doing wrong with this curl command:
```sh
curl -d'{"opaque_id":"einstein"}' -i https://marie:radioactivity@nc2.docker/index.php/apps/sciencemesh/~marie/api/user/GetUser
```
But I'm getting back a 302 to https://nc2.docker/index.php/apps/dashboard/

**Comment by michielbdejong** [comment]
Ah, it seems it's not even implemented :)

**Comment by michielbdejong** [comment]
The result of this curl call should be of the format `{"id":{"idp":"some-idp","opaque_id":"some-opaque-user-id","type":1}}` if a user called marie exists, and 404 otherwise.

**Comment by br0kk0l1** [comment]
You can use this I think, maybe you'll have to change some stuff(?):

https://github.com/pondersource/nc-sciencemesh/blob/main/lib/User/ScienceMeshUserId.php

**Comment by ishifoev** [comment]
When you are just try to call curl command when you are define a route with methods. You give error ```{"message":"CSRF check failed"}````

**Comment by ishifoev** [comment]
When you are run command a curl you are take 302. But if you are define the method and route, you are give another error 
````{"message":"CSRF check failed"}````

**Comment by ishifoev** [comment]
I think the problem that token is not pass. Need to see the original doc for reva. What we are see on the request data. 
https://cs3org.github.io/cs3apis/#cs3.identity.user.v1beta1.UserId

**Comment by Triantafullenia-Doumani** [comment]
> When you are run command a curl you are take 302. But if you are define the method and route, you are give another error `{"message":"CSRF check failed"}`

Solved: 

Put this comment above the GetUser()
```
/**
	 * @PublicPage
	 * @NoCSRFRequired
	 * @NoSameSiteCookieRequired
  */
```

**Comment by ishifoev** [comment]
@Triantafullenia-Doumani Yes you are right, thank you.

**Comment by michielbdejong** [comment]
https://github.com/pondersource/nc-sciencemesh/pull/161 is a good first step, let's build on that to make it give "soft-coded" responses.

**Comment by michielbdejong** [comment]
```sh
curl -d'{"opaque_id":"feinstein"}' -H 'Content-Type: application/json' -i http://alice:alice123@localhost/index.php/apps/sciencemesh/~alice/api/user/GetUser
```
