### ISSUE TITLE
Require http basic auth on api

### ISSUE THREAD

**Issue by ishifoev** [pondersource/nc-sciencemesh#167]
generate to token used to authenticate federated shares. We can create a new class that will be generate a secure token and in furture the problem like CSRF will not require. #148

**Comment by michielbdejong** [comment]
I don't think this is needed. Let's discuss!

**Comment by michielbdejong** [comment]
Hm, looks like this check is already in place?
When I try:
```sh
curl -d'{"opaque_id":"feinstein"}' -i http://alice:alice123@localhost/index.php/apps/sciencpi/user/GetUser
```
it works (returns a 200), but when I try:
```sh
curl -d'{"opaque_id":"feinstein"}' -i http://alice:alice13@localhost/index.php/apps/sciencpi/user/GetUser
```
it doesn't (returns a 401).
