### ISSUE TITLE
Allow generating an invite from the GUI

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#172]
It should make a  REST call to a configurable reva endpoint to get the token, and display that in the GUI.

**Comment by ishifoev** [comment]
We can't have do directly REST call to reva. We can do it inside the reva and get this token. How the curl command will return the info. I mean the curl request from pondersource.

**Comment by ishifoev** [comment]
https://github.com/pondersource/sciencemesh-nextcloud/issues/54

**Comment by ishifoev** [comment]
pondersource/sciencemesh-nextcloud#54
