### ISSUE TITLE
Wrong route for Authorize

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#175]
https://github.com/pondersource/nc-sciencemesh/blob/5834b68/appinfo/routes.php#L14 is wrong, it says
`'/~{userId}/api/storage/Authenticate'`
but that should be
`'/~{userId}/api/auth/Authenticate'`
instead.

**Comment by ishifoev** [comment]
I think it is working I do this curl command and it is give 200. 
```curl -v -H 'Content-Type:application/json' -d '{"password":"relativity"}' http://einstein:relativity@localhost/index.php/apps/sciencemesh/~einstein/api/storage/Authenticate```

**Comment by michielbdejong** [comment]
Ah, after @ylebre fixed this in #177 (but then closed that without merging), @ishifoev fixed it in #178 (but didn't close this issue).
I'll fix it for the 3rd time :)

**Comment by ishifoev** [comment]
@michielbdejong hah I put it on board that this task did. I didn't close I think maybe you test something.
