### ISSUE TITLE
ListSentShares() not workiing

### ISSUE THREAD

**Issue by Triantafullenia-Doumani** [pondersource/nc-sciencemesh#183]
curl
`curl -X POST http://marie:radioactivity@localhost:8080/index.php/apps/sciencemesh/~marie/api/ocm/ListSentShares`

server log

`
 {"Exception":"Exception","Message":"Call to undefined method OC\\DB\\QueryBuilder\\ExpressionBuilder\\SqliteExpressionBuilder::or() in file server\/apps\/sciencemesh\/lib\/ShareProvider\/ScienceMeshShareProvider.php' line 1191"`

**Comment by ishifoev** [comment]
Try change this line to 
```
$qb->expr()->orX(
					$qb->expr()->eq('uid_initiator', $qb->createNamedParameter($userId)),
					$qb->expr()->eq('uid_owner',$qb->createNamedParameter($userId))
				)
```
