### ISSUE TITLE
Accept Token for invite token generate

### ISSUE THREAD

**Issue by ishifoev** [pondersource/nc-sciencemesh#196]
We can test and working with generate token. We can accept the token if need to get from mock up. The first one need to working with actual Reva clii test it will be it work. The second need create another class for working with Reva endpoint. We can do some mock up for it. May be we need write some test case. Do we need save in DB that we can actually update something and change for GUI changes or we need work with mock up data?

**Comment by ishifoev** [comment]
```curl -i http://einstein:relativity@0.0.0.0:17001/ocm/invites/generate``` Test it is working for now

**Comment by ishifoev** [comment]
```curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"idp": "https://cernbox.cern.ch", "token": "dbc08800-553b-45d4-ad02-b542199648ab"}' \
 http://einstein:relativity@0.0.0.0:17001/ocm/invites/accept```

**Comment by ishifoev** [comment]
```{
  "code": "INVALID_PARAMETER",
  "message": "missing parameters in request"
}```

**Comment by ishifoev** [comment]
When you just set the param send for accept with curl command you can see that error 400. But we are not missing parameters in request

**Comment by michielbdejong** [comment]
I think it should be `/ocm/invites/forward` instead of `/ocm/invites/accept`

**Comment by ishifoev** [comment]
```curl --header "Content-Type: application/json"   --request POST   --data '{"idp": "https://cernbox.cern.ch, "token": dbc08800-553b-45d4-ad02-b542199648ab}'  http://einstein:relativity@0.0.0.0:19001/ocm/invites/forward````

**Comment by ishifoev** [comment]
````
{
  "code": "INVALID_PARAMETER",
  "message": "token and providerDomain must not be null"
}
```

**Comment by ishifoev** [comment]
Yeah the same think that we get 400 for token and providerDomain

**Comment by br0kk0l1** [comment]
```curl --header "Content-Type: application/x-www-form-urlencoded"   --request POST   --data "providerDomain=cernbox.cern.ch&token=b080f797-5592-4745-b38a-fef426330b86"  http://marie:radioactivity@localhost:17001/ocm/invites/forward```

**Comment by br0kk0l1** [comment]
so reva wants x-www-form and not json and it wants the field to be called providerDomain instead of idp

**Comment by ishifoev** [comment]
````
{  "code": "SERVER_ERROR",
  "message": "grpc forward invite request failed"
}
````

**Comment by ishifoev** [comment]
Yeah, I see the same problem may be in cli one time it is working one time not the same one when you would like to work with this endpoint.
