### ISSUE TITLE
GetMD returns 404 on root

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#2]
`curl -v  -d '{"path":"/"}' http://alice:alice123@localhost/apps/sciencemesh/~alice/api/GetMD`

returns a 404 even though /var/www/html/data/alice/files/sciencemesh/ exists

**Comment by michielbdejong** [comment]
I'll use https://github.com/pondersource/sciencemesh-nextcloud#how-to-use to investigate this

**Comment by michielbdejong** [comment]
From @ylebre via Slack:
> the `filesystem->has` is returning `false` for `'/'`
> so issue on my side, looking into it now

**Comment by ylebre** [comment]
flysystem normalizes '/' to '', which in turn always returns a file not found.
It is possible to pass a config to flysystem to skip the 'assertPresent' by setting disable_asserts to true. not sure we want to do this yet, so I've added a workaround to get the metadata directly and return that for now.

**Comment by michielbdejong** [comment]
Great! Can you also merge that workaround into the `main` branch in this repo? Then we can close this issue.

**Comment by ylebre** [comment]
Yes, please give me write access so I can do that :)

**Comment by michielbdejong** [comment]
Oops! :D
Should be fixed now, sorry.

**Comment by Triantafullenia-Doumani** [comment]
Should we have two options like this?
if ($path == "/") {
        $success = $this->filesystem->has($path);
	...
} else {
	....
}

**Comment by michielbdejong** [comment]
Yes, let's look at it together again tomorrow

**Comment by michielbdejong** [comment]
This was fixed by putting FlySystem on the userFolder instead of on the sciencemeshFolder.
