### ISSUE TITLE
Support Move

### ISSUE THREAD

**Issue by Triantafullenia-Doumani** [pondersource/nc-sciencemesh#20]
`move(from,to);` function doe's not exists in `vendor/league/flysystem/src/Filesystem.php` but in `vendor/league/flysystem/src/MountManager.php`.

So, an error occurs when trying to execute `$this->filesystem->move($from, $to);` at RevaController.php.

**Comment by michielbdejong** [comment]
This is a fundamental problem in how FlySystem works.
For now, we can just implement Move as Copy + Delete at the RevaController.php level.
We can improve later if necessary.

**Comment by michielbdejong** [comment]
Let's not support Move for now. We can add it later if we have time left.

**Comment by Triantafullenia-Doumani** [comment]
Ok, Great
