### ISSUE TITLE
trouble to fetch invitation token from reva.

### ISSUE THREAD

**Issue by navid-dada** [pondersource/nc-sciencemesh#220]
I am trying to generate an invitation token by Reva and show it in nc-sciencemesh  but I am facing with 404 error without any response body. 

when I am calling [invites/generate](http://mesh.pondersource.org/iop/invites/generate) it can find the route of Reva endpoint and it will trigger two API calls (authentication and home creating) but after these steps, it returns 404 error.

These are the logs that are printed in Revad log:

> 2022-08-29 18:52:38.28 INF src/github/cs3org/reva/internal/http/interceptors/auth/auth.go:258 > core access token generated pid=1 pkg=rhttp traceid=0490d565041ae25623aca049b2546abe

> 2022-08-29 18:52:38.28 INF src/github/cs3org/reva/internal/http/interceptors/providerauthorizer/providerauthorizer.go:83 > skipping provider authorizer check for: /invites/generate pid=1 pkg=rhttp traceid=0490d565041ae25623aca049b2546abe

> 2022-08-29 18:52:38.28 DBG src/github/cs3org/reva/pkg/rhttp/rhttp.go:255 > http routing: head=invites tail=/generate svc=not-found pid=1 pkg=rhttp

> 2022-08-29 18:52:38.28 WRN src/github/cs3org/reva/internal/http/interceptors/log/log.go:112 > http end="29/Aug/2022:18:52:38 +0000" host=10.1.86.241 method=POST pid=1 pkg=rhttp proto=HTTP/1.1 size=0 start="29/Aug/2022:18:52:37 +0000" status=404 time_ns=335132132 traceid=0490d565041ae25623aca049b2546abe uri=/invites/generate url=/invites/generate

I changed the URL to  [ocm/invites/generate](http://mesh.pondersource.org/iop/ocm/invites/generate) and the response changed to 401 without any extra info :(

**Comment by michielbdejong** [comment]
Could this be related to https://github.com/pondersource/sciencemesh-nextcloud/issues/71 maybe?

**Comment by navid-dada** [comment]
this is  related to issue #71

**Comment by navid-dada** [comment]
related to error #71
