### ISSUE TITLE
Sciencemesh client app GUI improvments.

### ISSUE THREAD

**Issue by navid-dada** [pondersource/nc-sciencemesh#229]
I checked the current version on the `frontend` branch and I think there should be some Improvements that make the app more user-friendly: 
1- Modify the `generate` page  to help the user to find out that the  **`Generate a new token`** is  clickable. 
2- Make a decision about the `Verify token`. Do you think it's necessary? we can replace it with a `COPY` button to put the token value inside the clipboard. 
![1-2](https://user-images.githubusercontent.com/10582747/210257279-beae74d5-a36f-4ae5-bdc2-0cec5bc6e6b3.jpg)

3- `Check token` should be changed to `Accept Token` on accept page.
4- An error will appear if the token is invalid. I think this message should have a red design if token validation failed or it should have a green design if token validation/acceptance flow was successful. 
![3-4](https://user-images.githubusercontent.com/10582747/210257295-25fa60e4-8794-4af0-b395-ed93ce204a73.jpg)

5- the phrase `No connection with Reva` should be changed to `No Sciencemesh Connection` and it should be more emphasized in design.
![5](https://user-images.githubusercontent.com/10582747/210257305-87efcde5-b789-4b06-9a82-f8743a38827f.jpg)

**Comment by navid-dada** [comment]
@parhamin2010

**Comment by parhamin2010** [comment]
@navid-dada, 
for number 2 it redirects to the another sciencemesh that verify the contact. Please let me know if you want to remove it.

**Comment by parhamin2010** [comment]
See here for instruction:
https://github.com/pondersource/oc-sciencemesh/issues/30

**Comment by parhamin2010** [comment]
![1](https://user-images.githubusercontent.com/25672014/211510724-4addc303-a8fe-4cff-8f9b-c0035bf22e57.png)
![3](https://user-images.githubusercontent.com/25672014/211510734-d4a56f6c-13d9-4157-b085-c185f49898c8.png)
![2](https://user-images.githubusercontent.com/25672014/211510739-665cfb61-70e1-429f-aebd-73e63433a678.png)

here're the fixes
