### ISSUE TITLE
GUI looks broken when installed on latest NC master

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#233]
Not sure if this is an incompatibility with Nextcloud 26 or some other reason but this is what I'm seeing when installing nc-sciencemesh on latest master of NC:

![Screenshot 2023-01-18 at 20 41 38](https://user-images.githubusercontent.com/408412/213279535-11e5388d-8000-41ef-a919-283a06f66eb1.png)

**Comment by michielbdejong** [comment]
@parhamin2010 can you try to reproduce this in your dev environment?
If you check out https://github.com/cs3org/ocm-test-suite/tree/nc-pr-testing in your dev environment, that will give you the right branches of Nextcloud and of the nc-sciencemesh app. You'll have to enable the sciencemesh app through the Apps panel (click once to allow, once to install).
Another option is to run Nextcloud from the master branch and install the nc-sciencemesh app, you will probably already be able to see this CSS problem.
@navid-dada can help you with the dev env set up to reproduce this if needed!

**Comment by parhamin2010** [comment]
@michielbdejong I reproduced it already. Just let me know what exactly I should check cause the CSS I check is working fine.

**Comment by michielbdejong** [comment]
In `view-source:https://nc1.docker/index.php/apps/sciencemesh/generate` on the nc-pr-testing branch of ocm-test-suite (don't forget to run `./rebuild.sh` after checking out that branch) I do see the `app-content` div with the Generate button etc. So it exists in the html tree but not on the screen.

**Comment by michielbdejong** [comment]
If I put 'display: none' on the app-navigation div, the app-content div becomes visible.

**Comment by michielbdejong** [comment]
In https://nc1.docker/index.php/apps/files/?dir=/&fileid=2 the layout is as desired, maybe we can learn from that

**Comment by parhamin2010** [comment]
The issue is related display value on parent div that needs to be flex or contents.
I'll add some more styles as well.

**Comment by michielbdejong** [comment]
@parhamin2010 any progress on this since yesterday? Do you think it's fixable?

**Comment by michielbdejong** [comment]
The way I'm working around this for testing is to open the web console and add `display: none` to the `app-navigation` div, but this is definitely unworkable and we should fix it asap.

**Comment by parhamin2010** [comment]
@michielbdejong I created PR here for this fix 
https://github.com/pondersource/nc-sciencemesh/pull/234

**Comment by michielbdejong** [comment]
Nm, it was browser cache. Awesome, thanks!
