### ISSUE TITLE
Check connection on admin setting dialogue for IOP URL

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/nc-sciencemesh#241]
Referred to this feature:
https://github.com/pondersource/sciencemesh-php/issues/90

**Comment by michielbdejong** [comment]
It seems there still is an issue with this; on commit `cbf5e489da` I'm not seeing any button:

![Screenshot 2023-02-13 at 10 45 05](https://user-images.githubusercontent.com/408412/218424715-462a815d-396a-4cb4-832c-340c8099b43b.png)
