### ISSUE TITLE
should Shared secret be randomly created string like loopback secret?

### ISSUE THREAD

**Issue by navid-shokri** [pondersource/nc-sciencemesh#244]
currently shared secret input is read-only but its value is constant and set to **_shared-secret -1_**
so we should make a decision about it there is a dilemma: 
1- shared secret value should be an automated randomly generated string?
2- shared secret should be editable and set by the system administrator? 

so according to [this](https://github.com/pondersource/nc-sciencemesh/blob/cbf5e489da161b030d40258b939c7b6fecc5e89b/lib/ServerConfig.php#L63) code, shared secret is randomly generated and it seems it generates once and is not editable.

**Comment by michielbdejong** [comment]
Generating a random string there is OK but it should be editable, because it needs to match the value in the Reva config.
