### ISSUE TITLE
Fix accept invitation messages UI

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/nc-sciencemesh#250]

**Comment by navid-shokri** [comment]
this is the final result of a successful attempt as I can see. :tada: 
![image](https://user-images.githubusercontent.com/123634558/222111374-5a7b9492-e0a3-4f20-a58c-25552853f618.png)
this is the final result of a failed attempt as I can see. :beers: : 
![image](https://user-images.githubusercontent.com/123634558/222111782-d76c024e-78c3-4fbe-a882-2a8cac30cc42.png)
