### ISSUE TITLE
GUI for "open with..."

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#257]
The “open with …” GUI needs to be available in the files app in some sort of right-click or “…” menu. 
You can just leave the controller method empty and just log "The user click open with HackMD" etc.
We need to populate the menu with multiple options. You can just fake the options from a mock array for now.
For instance you could mock the situation where both Einstein and Marie  have CodiMD installed, and Marie wants to open the file that was shared with her. Then the options array would be:
* "open with CodiMD"
* "open at source with CodiMD"

**Comment by mrvahedi68** [comment]
Here is some screen shots:

![open-with-1](https://user-images.githubusercontent.com/34796044/229456870-d45aa1c6-e7f3-4d5e-b795-00621476b8ee.JPG)
![open-with-2](https://user-images.githubusercontent.com/34796044/229456882-7f1181ff-86c9-4bcf-a82b-ec8ca3e51cb2.JPG)

**Comment by mrvahedi68** [comment]
Note: These items will only add to files with MIME equals to `text/plain`.
