### ISSUE TITLE
Searching contacts

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#259]
At the top of the ScienceMesh contacts pane, add a search input.
To test this, mock the ScienceMesh contacts of the current user, to have 1000 random names in there (you can just use randomly generated strings as the fake names).
When you type a text in the search box, the list should reduce to matching contacts.
A match could be on any part of the display name, the opaqueId or the providerDomain of the contact.

**Comment by mrvahedi68** [comment]
Here is the change in the UI:

![Screen Shot 1402-01-10 at 14 51 48](https://user-images.githubusercontent.com/34796044/228807184-034af87c-2b1c-4273-be87-681f69bd5018.png)

**Comment by parhamin2010** [comment]
Final PR for network beta is here:
https://github.com/pondersource/nc-sciencemesh/pull/311
