### ISSUE TITLE
OCM token not valid in share functionlity in Reva   

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/nc-sciencemesh#271]
Showing up this error after these steps:
1- git clone https://github.com/cs3org/reva
2- cd reva/
3- make
4- in root directory, run this: ./cmd/reva/reva -insecure -host localhost:19000
* run: login basic
* username einstein and password relativity
* run: ocm-invite-generate and copy the token value
5- In another bash run this : ./cmd/reva/reva -insecure -host localhost:19000
* run: login basic
* username einstein and password relativity
* run: ocm-invite-forward -idp cernbox.cern.ch -token <copied token value from above>

This error will show up:
error: code=CODE_INVALID_ARGUMENT msg="token not valid" support_trace="bbf06003ab5a1c7fb6dac455fd766103"
![image](https://user-images.githubusercontent.com/25672014/230087627-e49c899d-d9bf-4af4-8817-e518d82da9cd.png)

**Comment by michielbdejong** [comment]
@glpatcern can you have a look please?

**Comment by MahdiBaghbani** [comment]
fixed in Reva and now works fine.
