### ISSUE TITLE
Token URL redirection page doesn't have nc1 once we're using nrro-testing

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/nc-sciencemesh#274]
When we run nrro-testing.sh do the steps below you can find the issue:
1- run nrro-testing.sh
2- create a token url on oc2.docker
3- try to open the URL on another tab
you'll see this page without nc1.docker
![image](https://user-images.githubusercontent.com/25672014/230866847-68174266-a8e6-46bf-b018-3c7975fae020.png)

**Comment by michielbdejong** [comment]
You can edit this in https://github.com/michielbdejong/ocm-stub/blob/096e23a9ee5a6ecabe38f2d9de16bed4650bbbf7/stub.js#L276

**Comment by parhamin2010** [comment]
Fixed here
https://github.com/michielbdejong/ocm-stub/pull/2
