### ISSUE TITLE
sender name appears as "einstein@.docker" in accept-dialog

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#294]

**Comment by mrvahedi68** [comment]
[Here ](https://github.com/pondersource/server/blob/fd7087966a9a3c0194e8f4deebac9a89ea7f601a/apps/federatedfilesharing/js/external.js#L29) Nextcloud try to remove `https://` or `http://` from remote and because we have not `http` in the start of remote 7 characters removed from remote.
