### ISSUE TITLE
remote is set to reva1.com instead of efss1.com

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#298]
in the oc_share_external table on nc2.docker I'm seeing https://revanc1.docker instead of https://nc1.docker
if I update it, the share works.

**Comment by michielbdejong** [comment]
```
MariaDB [efss]> select * from oc_share_external;
+----+--------+------------+------------------------+-----------+----------------------------------+----------+-------+----------+-------+------------+----------------------------------+----------+
| id | parent | share_type | remote                 | remote_id | share_token                      | password | name  | owner    | user  | mountpoint | mountpoint_hash                  | accepted |
+----+--------+------------+------------------------+-----------+----------------------------------+----------+-------+----------+-------+------------+----------------------------------+----------+
|  1 |     -1 |          0 | https://revanc1.docker | 1         | 6aZv7NZDNCxOSQRx9IcuLgkDblTGHaxD |          | /asdf | einstein | marie | /asdf      | 3df744ba0de61015e2dbc8f4167c2fe7 |        1 |
+----+--------+------------+------------------------+-----------+----------------------------------+----------+-------+----------+-------+------------+----------------------------------+----------+
1 row in set (0.000 sec)

MariaDB [efss]> update oc_share_external set remote='https://nc1.docker';
Query OK, 1 row affected (0.001 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MariaDB [efss]>

**Comment by michielbdejong** [comment]
Ah! This line: 
https://github.com/michielbdejong/reva/blob/mentix-fixes/pkg/ocm/share/manager/nextcloud/nextcloud.go#L363

**Comment by michielbdejong** [comment]
And in the network-beta code that line is gone!
https://github.com/cs3org/reva/blob/master/pkg/ocm/share/repository/nextcloud/nextcloud.go

**Comment by michielbdejong** [comment]
So we need to add it back into https://github.com/cs3org/reva/blob/sciencemesh-dev/internal/grpc/services/ocmshareprovider/ocmshareprovider.go#L194-L199 !

**Comment by michielbdejong** [comment]
And that means the `webdav_host` config option should move from `[grpc.services.ocmshareprovider.drivers.nextcloud]` to `[grpc.services.ocmshareprovider]`

**Comment by redblom** [comment]
I can tell that without an efss (reva -> reva), that is the configuration that works.

**Comment by michielbdejong** [comment]
And https://github.com/pondersource/nc-sciencemesh/blob/sciencemesh/lib/Controller/OcmController.php#L500 is incorrect, it must use webdavOptions ... remote in the same way as `$protocol['webdavOptions']['sharedSecret'];` in the foreach loop around line 491 of that file.

**Comment by michielbdejong** [comment]
@glpatcern or @gmgigi96 can you take care of these changes on the reva side?

**Comment by gmgigi96** [comment]
@michielbdejong What do you expect to find as remote? Just something like https://cernbox.cern.ch?
Currently it's sending the full WebDAV endpoint

**Comment by michielbdejong** [comment]
Discuss with @labkode via email, we *want* the remote to be set to reva1.com in this case!
So we can close this. Sorry for the double work!
