### ISSUE TITLE
regular OCM not working in OC app?

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#304]
maybe I'm doing something wrong but this is what I see when I try to test regular OCM in the OC app:
<img width="1540" alt="Screenshot 2023-05-10 at 17 04 30" src="https://github.com/pondersource/nc-sciencemesh/assets/408412/a0d811ee-bc6f-411a-8ee7-0260d2859207">

**Comment by parhamin2010** [comment]
Reva is returning null value as I checked the logs:

![image](https://github.com/pondersource/nc-sciencemesh/assets/25672014/a85c8385-86ed-4aa6-ab4f-d9ab932f03cf)

**Comment by mrvahedi68** [comment]
That happens by switching to Network beta:
Before of this, we have accepted users on an attribute that is used here: https://github.com/pondersource/nc-sciencemesh/blob/aaa2a7e460f622daa629c9a31e4b9a144536970e/lib/Plugins/ScienceMeshSearchPlugin.php#L50

and Reva just returns:  `'[{"id":{"idp":"revaoc2.docker","opaque_id":"marie","type":1},"display_name":"marie"}]\n'`

We must change the science mesh for that.

**Comment by mrvahedi68** [comment]
This bug fixed. but have an error when sharing to Reva: Unexpected response code from EFSS API: 500

**Comment by michielbdejong** [comment]
This one is fixed, but see #309
