### ISSUE TITLE
Incorrect remote on webdav uri from Reva

### ISSUE THREAD

**Issue by mrvahedi68** [pondersource/nc-sciencemesh#306]
Reva sends incorrect remote URI on `addReceivedShare` API.
https://github.com/pondersource/nc-sciencemesh/blob/25aa1650124525c438ebb44d0db0a8c73fd7ffd4/lib/Controller/RevaController.php#LL945C6-L945C6

Received: remote.php/dav/ocm/acBFP5sqWXdd6jyeEnijDeMbFie9lYfL
Instead of: https://oc1.docker

**Comment by mrvahedi68** [comment]
Found the problem and fixed it on my local:
![image](https://github.com/pondersource/nc-sciencemesh/assets/34796044/78d3060e-e0a3-48ea-a7d1-36ee4ef8ab83)
![image](https://github.com/pondersource/nc-sciencemesh/assets/34796044/bbb88a2f-24d4-450e-b077-e9ad9fd9be25)

**Comment by mrvahedi68** [comment]
Reva needs to know `WebDavEndpoint` to create the `URL`. 
https://github.com/cs3org/reva/blob/f81247e9b27f1a90ab00200f2a6c6e233ee34cae/internal/grpc/services/ocmshareprovider/ocmshareprovider.go#L64

We do have not this in our config.

**Comment by michielbdejong** [comment]
Yes sorry, see https://github.com/cs3org/ocm-test-suite/commit/db40b01854e452c4c771b685bc0be8c325e20279

**Comment by michielbdejong** [comment]
And https://github.com/pondersource/dev-stock/commit/e3cecf9ff1fc37937c83f5f42c3061341dafae79
I'm building the Docker image now, will update here when pushed to Docker hub

**Comment by michielbdejong** [comment]
pondersource/dev-stock-revad-network-beta docker image pushed

**Comment by michielbdejong** [comment]
Sorry I forgot to build and push this yesterday after I fixed it in my own env!
