### ISSUE TITLE
Error on enabling app on OwnCloud

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/nc-sciencemesh#374]
Step to reproduce:
1- run the environment on dev-stock
2- run one of nrro/orro/orrn scripts
3- go to settings->apps
4- disable the sciencemesh app
5- enable it => you'll see the issue
here's the error message log:
`Class 'OCA\\\\ScienceMesh\\\\ScienceMeshProviderFactory' not found`

**Comment by michielbdejong** [comment]
Just comment out that config line while the app is disabled.
