### ISSUE TITLE
Deprecate "/api/Upload/... PUT" in favor of "/files/... PUT"?

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#5]
Can https://github.com/pondersource/nc-sciencemesh/blob/main/appinfo/routes.php#L46
Replace https://github.com/pondersource/nc-sciencemesh/blob/main/appinfo/routes.php#L39 ?

**Comment by ylebre** [comment]
You mean this line I think?
https://github.com/pondersource/nc-sciencemesh/blob/main/appinfo/routes.php#L33

I would like to have a 1 on 1 mapping of the Reva endpoints to Nextcloud if at all possible, to keep the translation as simple as possible. I would be in favor of letting both routes work.

**Comment by michielbdejong** [comment]
OK!

**Comment by michielbdejong** [comment]
So just to clarify,
For uploading I will use `POST /apps/sciencemesh/~tester/api/Upload/some/file/path.txt`
And for downloading I will use `GET /apps/sciencemesh/~tester/api/Download/some/file/path.txt` 
And I will not use the `/apps/sciencemesh/~tester/files/` route at all, right?
