### ISSUE TITLE
What is the difference between GetShare() and GetReceivedShare()

### ISSUE THREAD

**Issue by Felicia-Doumani** [pondersource/nc-sciencemesh#50]
By the [Interface that manipulates shares on Reva side](https://github.com/cs3org/reva/blob/master/pkg/share/share.go) we know:

* `GetShare()` : gets the information for a share by the given ref

* `GetReceivedShare()` : returns the information for a received share the user has access.

So, as I understand the only difference is:
* GetShare() will return a share( no matter who created it) 
* GetReceivedShare() will return a share someone else created( because it is a received share).

In every case, the user needs to have access to the share, and we get the share by the unique id.

If (this is the only difference):
- Why do we need 2 methods for that?

else : 
- What are the differences?

**Comment by michielbdejong** [comment]
See also https://github.com/cs3org/reva/issues/2148 and https://github.com/cs3org/cs3apis/issues/150
