### ISSUE TITLE
"Please specify a valid group" 

### ISSUE THREAD

**Issue by Triantafullenia-Doumani** [pondersource/nc-sciencemesh#52]
To create a new share, we need to call :

`$this->groupManager->groupExists($shareWith) ` at [ShareAPIController.php](https://github.com/nextcloud/server/blob/27865d0/apps/files_sharing/lib/Controller/ShareAPIController.php#L515)

But, when we run the Reva Unit test for Share, we get this error:

"[Please specify a valid group](https://github.com/nextcloud/server/blob/27865d0/apps/files_sharing/lib/Controller/ShareAPIController.php#L516)"

**Comment by michielbdejong** [comment]
For now, just implement sharing with a user, we can implement sharing with a group later.
