### ISSUE TITLE
ListReceivedShares() is not working

### ISSUE THREAD

**Issue by Triantafullenia-Doumani** [pondersource/nc-sciencemesh#93]
First, we shared a folder with Marie.

We have 2 ways to check the new share

* :heavy_check_mark: We can see this new share at _http://localhost:8080/index.php/apps/files/?dir=/&view=sharingin_  (working)

* :x: Use a curl command to call   [ListReceivedShares()](https://github.com/pondersource/nc-sciencemesh/blob/6215c61/lib/Controller/RevaController.php#L964) (not working)
```
curl -X POST http://marie:radioactivity@localhost:8080/index.php/apps/sciencemesh/~marie/api/ocm/ListReceivedShares

```
Curl returns an empty array :disappointed: 

### Server logs

* Undefined offset #103
* Could not detect any host in cern.ch/ocs-provider/ #105
* Invalid webdav storage configuration #104

### 1) Investigate ListReceivedShares()

[ListReceivedShares()](https://github.com/pondersource/nc-sciencemesh/blob/6215c61/lib/Controller/RevaController.php#L964) 

:point_down:

  [$this->shareManager->getSharedWith()](https://github.com/nextcloud/server/blob/9068fd4/lib/private/Share20/Manager.php#L1362)  

:point_down: 

 [$provider->getSharedWith()](https://github.com/nextcloud/server/blob/df4e6bab6938287e7c0a876bdeacb7e0d8617723/apps/federatedfilesharing/lib/FederatedShareProvider.php#L794) 

:point_down: 

[$this->dbConnection->getQueryBuilder()](https://github.com/nextcloud/server/blob/df4e6bab6938287e7c0a876bdeacb7e0d8617723/lib/private/DB/ConnectionAdapter.php#L49)

:point_down: 

[$this->inner->getQueryBuilder()](https://github.com/nextcloud/server/blob/df4e6bab6938287e7c0a876bdeacb7e0d8617723/lib/private/DB/Connection.php#L101)

:point_down: 

Returns a [QueryBuilder](https://github.com/nextcloud/server/blob/df4e6bab6938287e7c0a876bdeacb7e0d8617723/lib/private/DB/QueryBuilder/QueryBuilder.php#L58) object

### 2) Info from URL

Shares shared with you: http://localhost:8080/index.php/apps/files/?dir=/&view=sharingin

**Comment by michielbdejong** [comment]
spec for list (sent?): https://github.com/cs3org/reva/blob/8697c15/pkg/ocm/share/manager/nextcloud/nextcloud_server_mock.go#L50
spec for list received: https://github.com/cs3org/reva/blob/8697c15/pkg/ocm/share/manager/nextcloud/nextcloud_server_mock.go#L51
